<?php /** @var TNW_Salesforce_Block_Adminhtml_System_Config_Frontend_Fees_Synchronize $this */ ?>
<script type="text/javascript">
    //<![CDATA[
    function fees_synchronize() {
        Form.Element.disable('fees_synchronize_button');
        $('fees_synchronize_button').addClassName('disabled');
        $('fees_sync_span').removeClassName('no-display');

        setLocation('<?php echo $this->getUrl('adminhtml/tool_fees/create') ?>');
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>
<span class="sync-indicator no-display" id="fees_sync_span">
    <img alt="Synchronize" style="margin:0 5px" src="<?php echo $this->getSkinUrl('images/process_spinner.gif') ?>"/>
</span>