<?php
/** @var TNW_Salesforce_Block_Adminhtml_Sales_Order_View_Salesforce $this */
?>
<div id="tnw-order-info-block" style="display: none">
    <div class="box-right entry-edit">
        <div class="entry-edit-head"><h4><?php echo Mage::helper('tnw_salesforce')->__('Sales Person') ?></h4></div>
        <fieldset>
            <span class="field-row"><?php echo $this->getFormHtml();?></span>
            <div class="f-right">
                <?php echo $this->getSaveButtonHtml() ?>
            </div>
        </fieldset>
    </div>
    <script type="application/javascript">
        jQuery('#sales_order_view_tabs_order_info_content .order-totals')
            .parent('.box-right')
            .before(jQuery('#tnw-order-info-block > div'));
    </script>
</div>