<?php
/** @var TNW_Salesforce_Block_Adminhtml_Sales_Order_Create_Salesforce $this */
?>
<div id="tnw-order-info-block" style="display: none">
    <div class="box-right entry-edit tnw-entry-salesforce">
        <div class="entry-edit-head"><h4><?php echo Mage::helper('tnw_salesforce')->__('Sales Person') ?></h4></div>
        <fieldset><?php echo $this->getFormHtml();?></fieldset>
    </div>
    <script type="application/javascript">
        jQuery(document).ready(function() {
            jQuery('.main-col .order-totals')
                .parent('.box-right')
                .before(jQuery('#tnw-order-info-block > div'));
        });
    </script>
</div>