<?php

/**
 * Author: Tech-N-Web, LLC (dba PowerSync)
 * Email: support@powersync.biz
 * Developer: Evgeniy Ermolaev
 * Date: 27.05.15
 * Time: 15:22
 */
class TNW_Salesforce_Block_Adminhtml_Tool_Console_Form_Grid extends Mage_Adminhtml_Block_Widget_Grid
{
    /**
     * Pager visibility
     *
     * @var boolean
     */
    protected $_pagerVisibility = false;

    /**
     * Filter visibility
     *
     * @var boolean
     */
    protected $_filterVisibility = false;

    /**
     * @param array $attributes
     */
    public function __construct($attributes = array())
    {
        parent::__construct($attributes); // TODO: Change the autogenerated stub

        $collection = Mage::registry('sql_result');

        $this->setCollection($collection);
    }

    /**
     * @return $this
     */
    protected function _prepareCollection()
    {
        return $this;
    }

    protected function _prepareColumns()
    {

        if (empty($this->_collection)) {
            return parent::_prepareColumns();
        }

        foreach ($this->_collection as $item) {
            foreach ($item->getData() as $field => $value) {

                if (!$this->getColumn($field)) {
                    $this->addColumn($field,
                        array(
                            'header' => $this->__($field),
                            'width' => '50px',
                            'index' => $field
                        )
                    );
                }
            }
        }

        return parent::_prepareColumns();
    }
}
