<?php

class TNW_Salesforce_Block_Adminhtml_Sales_Order_View_Salesforce extends Mage_Adminhtml_Block_Widget_Form
{
    protected function _prepareForm()
    {
        $form = new Varien_Data_Form(array(
            'id' => 'salesforce_edit_form',
            'action' => $this->getUrl(
                '*/sales_order/saveSalesforce',
                array(
                    'order_id' => $this->getOrder()->getId(),
                )
            ),
            'method' => 'post',
            'enctype' => 'multipart/form-data'
        ));

        $form->setUseContainer(true);
        $form->setFieldNameSuffix('order');

        /** @var TNW_Salesforce_Block_Adminhtml_Widget_Form_Renderer_Fieldset_Owner $rendererOwner */
        $rendererOwner = Mage::getSingleton('core/layout')
            ->createBlock('tnw_salesforce/adminhtml_widget_form_renderer_fieldset_owner');

        $form
            ->addField('owner_salesforce_id', 'text', array(
                'name' => 'owner_salesforce_id',
                'selector'  => 'tnw-ajax-find-select-owner-info'
            ))
            ->setRenderer($rendererOwner);

        $form->setValues($this->getOrder()->getData());
        $this->setForm($form);
    }

    /**
     * Retrieve order model instance
     *
     * @return Mage_Sales_Model_Order
     */
    public function getOrder()
    {
        return Mage::registry('current_order');
    }

    public function getSaveButtonHtml()
    {
        $button = $this->getLayout()->createBlock('adminhtml/widget_button')
            ->setData(array(
                'label' => Mage::helper('tnw_salesforce')->__('Save Salesforce Data'),
                'onclick' => "$('salesforce_edit_form').submit();",
                'class' => 'save'
            ));

        return $button->toHtml();
    }

    protected function _toHtml()
    {
        if (!Mage::helper('tnw_salesforce')->isEnabled() || !Mage::helper('tnw_salesforce')->isEnabledOrderSync()) {
            return '';
        }

        return parent::_toHtml(); // TODO: Change the autogenerated stub
    }
}